// <auto-generated />
using Ivanov_Denis_Evgenievich_KT_31_23.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ivanov_Denis_Evgenievich_KT_31_23.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918214350_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisciplineId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            DisciplineId = 1,
                            IsDeleted = false,
                            Name = "Базы данных"
                        },
                        new
                        {
                            DisciplineId = 2,
                            IsDeleted = false,
                            Name = "Программирование"
                        });
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            DisciplineId = 1,
                            StudentId = 1,
                            Value = 5
                        },
                        new
                        {
                            GradeId = 2,
                            DisciplineId = 2,
                            StudentId = 1,
                            Value = 4
                        },
                        new
                        {
                            GradeId = 3,
                            DisciplineId = 1,
                            StudentId = 2,
                            Value = 3
                        },
                        new
                        {
                            GradeId = 4,
                            DisciplineId = 2,
                            StudentId = 3,
                            Value = 5
                        });
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("Course")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Course = 3,
                            IsDeleted = false,
                            Name = "КТ-31-23",
                            SpecialtyId = 1
                        },
                        new
                        {
                            GroupId = 2,
                            Course = 3,
                            IsDeleted = false,
                            Name = "КТ-32-23",
                            SpecialtyId = 1
                        },
                        new
                        {
                            GroupId = 3,
                            Course = 3,
                            IsDeleted = false,
                            Name = "ПИ-31-23",
                            SpecialtyId = 2
                        });
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecialtyId");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            SpecialtyId = 1,
                            Code = "09.03.02",
                            Title = "Информационные системы и технологии"
                        },
                        new
                        {
                            SpecialtyId = 2,
                            Code = "09.03.03",
                            Title = "Прикладная информатика"
                        });
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Денис",
                            GroupId = 1,
                            IsDeleted = false,
                            LastName = "Иванов"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Иван",
                            GroupId = 1,
                            IsDeleted = false,
                            LastName = "Петров"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Анна",
                            GroupId = 2,
                            IsDeleted = false,
                            LastName = "Смирнова"
                        });
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Grade", b =>
                {
                    b.HasOne("Ivanov_Denis_Evgenievich_KT_31_23.Models.Discipline", "Discipline")
                        .WithMany("Grades")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivanov_Denis_Evgenievich_KT_31_23.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Group", b =>
                {
                    b.HasOne("Ivanov_Denis_Evgenievich_KT_31_23.Models.Specialty", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Student", b =>
                {
                    b.HasOne("Ivanov_Denis_Evgenievich_KT_31_23.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Discipline", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Specialty", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Ivanov_Denis_Evgenievich_KT_31_23.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
